package Lab5_Re;
import simView.*;
import java.awt.*;

public class ef extends ViewableDigraph
{
	
	public ef()
	{
		this("ef", 20, 1000);
	}
	
	public ef(String name, double int_arr_t, double observe_t)
	{
		super(name);
		
		addInport("in"); 
		addOutport("out");
		ViewableAtomic t = new transd("t", observe_t); // ef 내부에는 genr와 transd로 구성
		ViewableAtomic g = new genr("g", int_arr_t);

		add(g);
		add(t);
		
		addCoupling(t, "out", g, "in"); // t.out -> g.in
		addCoupling(g, "out", t, "ariv"); // g.out -> t.arive
		addCoupling(this, "in", t, "solved"); // ef.in -> t.solved
		addCoupling(g, "out", this, "out"); // g.out -> ef.out의 방향으로 coupling
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(463, 297);
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(116, 60));
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(108, 185));
    }
}
