package Lab5_Re;
import java.awt.*;
import simView.*;

public class efQproc extends ViewableDigraph 
{

	public efQproc()
	{
		super("efQproc");
		
		ViewableAtomic qp = new procQ("Qproc", 15); // processing time = 15의 parameter로 instance
		ViewableDigraph  expf = new ef("EF", 10, 300); // int_arr_time(genr에서 job생성주기) = 10, transd 에서의 observation time = 300

		add(expf);
		add(qp);

		addCoupling(expf, "out", qp, "in"); // 커플링 기존 efp에서 변화 없음
		addCoupling(qp, "out", expf, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("EF")).setPreferredLocation(new Point(54, 121));
        ((ViewableComponent)withName("Qproc")).setPreferredLocation(new Point(626, 287));
    }
 }
