package Lab4;
import java.awt.*;
import simView.*;

public class gprocQ extends ViewableDigraph
{

	public gprocQ()
	{
		super("gprocQ");
    	
		ViewableAtomic g = new genr("g", 20); // initail time = 20
		ViewableAtomic p = new procQ("p", 35); // processing time 35
		ViewableAtomic t = new transd("t", 190);
    	
		add(g);
		add(p);
		add(t);
		
		addCoupling(g, "out", p, "in"); // g_out -> p_in
		addCoupling(t, "out", g, "in");
		addCoupling(g, "out", t, "ariv");
		addCoupling(p, "out", t, "solved");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(301, 109));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(229, 342));
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(451, 269));
    }
}
