package Lab3;
import java.awt.*;
import simView.*;

public class modified_gpt extends ViewableDigraph
{

	public modified_gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new modified_genr("g", 30);
		ViewableAtomic p = new modified_proc("p", 40); // processing time = 40
		ViewableAtomic t = new modified_transd("t", 1000); // observation time = 1000
    	
		add(g);
		add(p);
		add(t);
  
		addCoupling(g, "out", p, "in");
		addCoupling(g, "out", t, "ariv");
		
		addCoupling(p, "out", t, "solved");
     
		addCoupling(t, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(382, 115));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(74, 428));
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(471, 449));
    }
}
