package Lab8;
import java.awt.*;
import simView.*;

public class LRSM extends ViewableDigraph
{
	final int NODE = 6;
	int[] proc_t = {0, 20, 15, 30, 50, 40, 25};// 과제할때 바꿀곳
	int[] q_size = {0, 3, 5, 4, 3, 5, 3};
	
	public LRSM()
	{
		super("LRSM");
    			
		ViewableAtomic g = new genr("genr", 5);
		ViewableAtomic s = new scheduler("scheduler", 0, NODE, q_size);
		ViewableAtomic t = new transd("transducer", 5000);
    	
		add(g);
		add(s);
		add(t);
  
		addCoupling(g, "out", s, "in");
		addCoupling(g, "out", t, "ariv");
		addCoupling(t, "out", g, "in");
		

		addCoupling(s, "out_loss", t, "loss");
		for(int i = 1; i <= NODE; i++) {
			ViewableAtomic p = new processor("processor" + i, proc_t[i] , q_size[i]);
			add(p);
			
			addCoupling(p, "out", t, "solved");
			addCoupling(p, "out", s, "in" + i);
			
			addCoupling(s, "out" + i, p, "in");
		}
		
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(-27, 237));
        ((ViewableComponent)withName("processor4")).setPreferredLocation(new Point(373, 372));
        ((ViewableComponent)withName("processor3")).setPreferredLocation(new Point(378, 279));
        ((ViewableComponent)withName("processor5")).setPreferredLocation(new Point(379, 453));
        ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(651, 219));
        ((ViewableComponent)withName("processor2")).setPreferredLocation(new Point(374, 182));
        ((ViewableComponent)withName("scheduler")).setPreferredLocation(new Point(205, 211));
        ((ViewableComponent)withName("processor6")).setPreferredLocation(new Point(374, 522));
        ((ViewableComponent)withName("processor1")).setPreferredLocation(new Point(371, 78));
    }
}
