package Lab8_HW;
import java.awt.*;
import simView.*;

public class LRSM extends ViewableDigraph
{
	final int NODE = 6;
	
	int[] proc_t = {0, 25, 15, 30, 50, 40, 25};
//	double[] q_size = {0, 2, 3, 4, 5, 4};
	int[] q_size = {0, 3, 5, 4, 3, 5, 3};
	
	
	public LRSM()
	{
		super("LRSM");
    			
		ViewableAtomic g = new genr("genr", 4);
		ViewableAtomic s = new scheduler("scheduler", 0, NODE, q_size);
		ViewableAtomic t = new transd("t", 5000);
    	
		add(g);
		add(s);
		add(t);
  
		addCoupling(g, "out", s, "in");
		addCoupling(g, "out", t, "ariv");
		
		addCoupling(t, "out", g, "in");
		
		addCoupling(s, "out_loss", t, "loss");
		
		for(int i = 1; i <= NODE; i++) {
			ViewableAtomic p = new processor("processor" + i, proc_t[i], q_size[i]);
			add(p);
			
			addCoupling(p, "out", t, "solved");
			addCoupling(p, "out", s, "in" + i);
			
			addCoupling(s, "out" + i, p, "in");
		}
		
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("processor2")).setPreferredLocation(new Point(468, 159));
        ((ViewableComponent)withName("scheduler")).setPreferredLocation(new Point(181, 259));
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(784, 232));
        ((ViewableComponent)withName("processor1")).setPreferredLocation(new Point(460, 25));
        ((ViewableComponent)withName("processor6")).setPreferredLocation(new Point(466, 522));
        ((ViewableComponent)withName("processor3")).setPreferredLocation(new Point(462, 270));
        ((ViewableComponent)withName("processor4")).setPreferredLocation(new Point(470, 363));
        ((ViewableComponent)withName("processor5")).setPreferredLocation(new Point(456, 442));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(17, 151));
    }
}
