package Lab2;
import java.awt.*;
import simView.*;

public class gproc extends ViewableDigraph // 커플링하는 거는 diagraph extend
{

	public gproc()
	{
		super("gproc");
    	
		ViewableAtomic g = new genr("g", 30); // generator는 30의 sigma
		ViewableAtomic p = new proc("p", 40); // processor는 40의 sigma

    	
		add(g);
		add(p);
  
		addCoupling(g, "out", p, "in"); // g_out -> p_in
		addCoupling(p, "out", g, "in");	// p_in -> g_out
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(67, 233));
    }
}
