package Lab2;
import java.awt.*;
import simView.*;

public class modified_gproc extends ViewableDigraph
{

	public modified_gproc()
	{
		super("gproc");
    	
		ViewableAtomic g = new modified_genr("modified_genr", 40); // 지난주 과제물인 modified_genr의 initial sigma = 40
		ViewableAtomic p = new proc("proc", 45); // 이번주 과제에 주어진 processing time = 45, gproc과 헷갈릴 수 있으므로 이름을 변경

    	
		add(g);
		add(p);
  
		addCoupling(g, "out", p, "in"); // g_out -> p_in
		addCoupling(p, "out", g, "in");	// p_in -> g_out
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("proc")).setPreferredLocation(new Point(52, 201));
        ((ViewableComponent)withName("modified_genr")).setPreferredLocation(new Point(50, 50));
    }
}
