package Lab7;
import java.awt.*;
import simView.*;

public class RRSM extends ViewableDigraph
{
	final int NODE = 6;
	final int QUEUE = 2;
	
	public RRSM()
	{
		super("RRSM");
    			
		ViewableAtomic g = new genr("genr", 30);
		ViewableAtomic s = new scheduler("scheduler", 0, NODE);
		ViewableAtomic t = new transd("t", 4500, NODE);
    	
		add(g);
		add(s);
		add(t);
  
		addCoupling(g, "out", s, "in");
		addCoupling(g, "out", t, "ariv");
		addCoupling(t, "out", g, "in");
		
		for(int i = 1; i <= NODE; i++) {
			ViewableAtomic p = new processor("processor" + i, (120 + (20 * (i - 1))), QUEUE);
			add(p);
			
			addCoupling(p, "out1", t, "solved");
			addCoupling(p, "out2", t, "loss");
			
			addCoupling(s, "out" + i, p, "in");
		}
		
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(84, 45));
        ((ViewableComponent)withName("processor2")).setPreferredLocation(new Point(456, 101));
        ((ViewableComponent)withName("processor5")).setPreferredLocation(new Point(450, 359));
        ((ViewableComponent)withName("processor4")).setPreferredLocation(new Point(455, 278));
        ((ViewableComponent)withName("scheduler")).setPreferredLocation(new Point(197, 221));
        ((ViewableComponent)withName("processor3")).setPreferredLocation(new Point(455, 187));
        ((ViewableComponent)withName("processor1")).setPreferredLocation(new Point(460, 25));
        ((ViewableComponent)withName("processor6")).setPreferredLocation(new Point(450, 451));
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(784, 232));
    }
}
