package Lab6;
import java.awt.*;
import simView.*;

public class CSM2 extends ViewableDigraph
{

	public CSM2()
	{
		super("Client_Server_Model");
    	
		ViewableAtomic c = new client("Client", 30);
		ViewableAtomic s = new server("Server", 10);
    	
		add(c);
		add(s);

		addCoupling(c, "out", s, "in");
		addCoupling(s, "out", c, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("Server")).setPreferredLocation(new Point(345, 376));
        ((ViewableComponent)withName("Client")).setPreferredLocation(new Point(355, 207));
    }
}
