package Lab5_ex;
import simView.*;
import java.awt.*;

public class Boss extends ViewableDigraph
{
	
	public Boss()
	{
		super("Boss_Diagraph");
		
		
		ViewableAtomic p = new proc("proc_atomic", 10);
		ViewableDigraph gd = new genr_diagraph("genr_diagraph", 10);

		add(gd);
		add(p);

		addCoupling(gd, "out", p, "in");

		addCoupling(p, "out", gd, "in");
	}
	
	//생성자 오버로딩을 할 필요가 없음

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(774, 500);
        ((ViewableComponent)withName("genr_diagraph")).setPreferredLocation(new Point(277, 60));
        ((ViewableComponent)withName("proc_atomic")).setPreferredLocation(new Point(382, 431));
    }
}
