package Lab5_ex;
import simView.*;
import java.awt.*;

public class genr_diagraph extends ViewableDigraph
{
	
	public genr_diagraph()
	{
		this("genr_diagraph", 30);
	}
	
	public genr_diagraph(String name, double int_arr_t)
	{
		super(name);
		
		addInport("in"); 
		addOutport("out");
		
		ViewableAtomic g = new genr("genr_atomic", int_arr_t);


		add(g);

		addCoupling(g, "out", this, "out");
		addCoupling(this, "in", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(475, 309);
        ((ViewableComponent)withName("genr_atomic")).setPreferredLocation(new Point(111, 100));
    }
}
